// <auto-generated />
using System;
using Leaderboard.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Leaderboard.Infrastructure.Migrations
{
    [DbContext(typeof(LeaderboardDbContext))]
    partial class LeaderboardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Leaderboard.Domain.Entities.Achievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("name");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("operator");

                    b.Property<Guid>("StatisticId")
                        .HasColumnType("uuid")
                        .HasColumnName("id_statistic");

                    b.Property<int>("Threshold")
                        .HasColumnType("integer")
                        .HasColumnName("threshold");

                    b.HasKey("Id");

                    b.HasIndex("StatisticId");

                    b.ToTable("achievements", (string)null);
                });

            modelBuilder.Entity("Leaderboard.Domain.Entities.Hero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ClassId")
                        .HasColumnType("integer")
                        .HasColumnName("id_class");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("id_player");

                    b.Property<string>("Pseudo")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("pseudo");

                    b.Property<int>("Score")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("score");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("Score");

                    b.HasIndex("ClassId", "Score");

                    b.ToTable("heroes", (string)null);
                });

            modelBuilder.Entity("Leaderboard.Domain.Entities.HeroAchievement", b =>
                {
                    b.Property<Guid>("AchievementId")
                        .HasColumnType("uuid")
                        .HasColumnName("id_achievement");

                    b.Property<Guid>("HeroId")
                        .HasColumnType("uuid")
                        .HasColumnName("id_hero");

                    b.Property<DateTimeOffset>("ObtainedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("obtained_at");

                    b.HasKey("AchievementId", "HeroId");

                    b.HasIndex("HeroId");

                    b.ToTable("hero_achievements", (string)null);
                });

            modelBuilder.Entity("Leaderboard.Domain.Entities.HeroClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("classes", (string)null);
                });

            modelBuilder.Entity("Leaderboard.Domain.Entities.HeroStatistic", b =>
                {
                    b.Property<Guid>("HeroId")
                        .HasColumnType("uuid")
                        .HasColumnName("id_hero");

                    b.Property<Guid>("StatisticId")
                        .HasColumnType("uuid")
                        .HasColumnName("id_statistic");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Value")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("value");

                    b.HasKey("HeroId", "StatisticId");

                    b.HasIndex("StatisticId", "Value");

                    b.ToTable("hero_statistics", (string)null);
                });

            modelBuilder.Entity("Leaderboard.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("PlayerId");

                    b.Property<int>("Attack")
                        .HasColumnType("integer")
                        .HasColumnName("PlayerAttack");

                    b.Property<int>("Health")
                        .HasColumnType("integer")
                        .HasColumnName("PlayerHealth");

                    b.Property<int>("MaxHealth")
                        .HasColumnType("integer")
                        .HasColumnName("PlayerMaxHealth");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("PlayerName");

                    b.HasKey("Id");

                    b.ToTable("Players", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Leaderboard.Domain.Entities.Statistic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("CountsInScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("counts_in_score");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsSortable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_sortable");

                    b.Property<int>("Multiplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("multiplier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("statistics", (string)null);
                });

            modelBuilder.Entity("Leaderboard.Domain.Entities.Achievement", b =>
                {
                    b.HasOne("Leaderboard.Domain.Entities.Statistic", "Statistic")
                        .WithMany("Achievements")
                        .HasForeignKey("StatisticId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Statistic");
                });

            modelBuilder.Entity("Leaderboard.Domain.Entities.Hero", b =>
                {
                    b.HasOne("Leaderboard.Domain.Entities.HeroClass", "Class")
                        .WithMany("Heroes")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("Leaderboard.Domain.Entities.HeroAchievement", b =>
                {
                    b.HasOne("Leaderboard.Domain.Entities.Achievement", "Achievement")
                        .WithMany("HeroAchievements")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Leaderboard.Domain.Entities.Hero", "Hero")
                        .WithMany("HeroAchievements")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("Hero");
                });

            modelBuilder.Entity("Leaderboard.Domain.Entities.HeroStatistic", b =>
                {
                    b.HasOne("Leaderboard.Domain.Entities.Hero", "Hero")
                        .WithMany("HeroStatistics")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Leaderboard.Domain.Entities.Statistic", "Statistic")
                        .WithMany("HeroStatistics")
                        .HasForeignKey("StatisticId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hero");

                    b.Navigation("Statistic");
                });

            modelBuilder.Entity("Leaderboard.Domain.Entities.Achievement", b =>
                {
                    b.Navigation("HeroAchievements");
                });

            modelBuilder.Entity("Leaderboard.Domain.Entities.Hero", b =>
                {
                    b.Navigation("HeroAchievements");

                    b.Navigation("HeroStatistics");
                });

            modelBuilder.Entity("Leaderboard.Domain.Entities.HeroClass", b =>
                {
                    b.Navigation("Heroes");
                });

            modelBuilder.Entity("Leaderboard.Domain.Entities.Statistic", b =>
                {
                    b.Navigation("Achievements");

                    b.Navigation("HeroStatistics");
                });
#pragma warning restore 612, 618
        }
    }
}
